# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            cd frontend
            docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-front .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-front
      - run:
          name: Install oc
          command: |
            cd /tmp
            wget --no-check-certificate https://downloads-openshift-console.apps.$OC_SERVER/amd64/linux/oc.tar
            tar -xvf oc.tar
            mkdir ~/.local && mkdir ~/.local/bin
            cp oc ~/.local/bin
      - run:
          name: Import new image to OpenShift
          command: |
            oc login --insecure-skip-tls-verify=true -u $OC_LOGIN -p $OC_PWD https://api.$OC_SERVER:6443
            oc import-image docker.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-front
