# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
  docker: circleci/docker@1.0.1
# Orchestrate or schedule a set of jobs
# workflows:
#   # Name the workflow "welcome"
#   frontend:
#     # Run the welcome/run job in its own container
#     jobs:
#       - docker/build:
#           path: frontend
#           debug: true
#           image: joellord/circleci-front
#       - docker/push:
#           image: joellord/circleci-front

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      # - run:
      #     name: Build and push Docker image
          # command: |
          #   cd frontend
          #   docker build -t joellord/circleci-front .
          #   echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          #   docker push joellord/circleci-front
      - run:
          name: Install oc
          command: |
            cd /tmp
            curl --insecure -I https://downloads-openshift-console.apps.ci-ln-lgfgci2-d5d6b.origin-ci-int-aws.dev.rhcloud.com/amd64/linux/oc.tar --output oc.tar
            tar -xvf oc.tar
            echo $(ls)